### ISSUE TITLE
not clear usage

### ISSUE THREAD

**Issue by mazorigal** [Backline/akka-http-metrics#11]
Hi,

the example how to use the metrics with akka http is not so much clear.

```
trait MyRoute extends Directives {
  def myRoute = {
    timerDirective {
      (get & path("ping")) {
        complete("pong")
      }
    }
  }
}
```

I guess in order to use timerDirective the trait MyRoute first need to be extended with HttpTimerMetrics ?

Also, how can I control the name of the different metrics ?
I have for the moment the following route:

```
pathPrefix("internal" / "user-profile") {
    (get & path(Segment / Segment)) { (uid, uidType) =>
        timerDirective {complete {...}}
    }
}
```

and what I get in Graphite is metrics for each call as following:
myPrefix.internal.user-profile.uid1.client.GET
myPrefix.internal.user-profile.uid77.client.GET

I would like to have total metrics for the route /internal/user-profile

Is it possible ?

Thanks,

**Comment by adamdecaf** [comment]
Whoops. I fixed the readme to mixin the proper trait. -- https://github.com/Backline/akka-http-metrics#example-usage

There's currently no way to specify a custom name, but I think it'd be pretty easy to do. I'll take a few minutes and see what I can come up with.

**Comment by adamdecaf** [comment]
@mazorigal I went ahead and created https://github.com/Backline/akka-http-metrics/pull/12. Thoughts? It would add new functions that you'd use to specify custom metric names.

**Comment by mazorigal** [comment]
Great, thanks.
looks fine to me.
any option to add the custom name functionality to the response codes metrics as well ?
the user can provide some sort of mapping function in order to map the different response codes to custom names or to overwrite the  liftStatusCode function

**Comment by adamdecaf** [comment]
@mazorigal I forgot about those. I've added the same change for them https://github.com/Backline/akka-http-metrics/pull/12/commits/e56f2ba095c16e25e6ecd8dd5791389eb7b8bd10

Thoughts?

**Comment by mazorigal** [comment]
Thanks, looks fine to me.
when could you merge it to master ?

**Comment by adamdecaf** [comment]
`0.4.1` has been released. Let me know if you run into any issues, thanks!

https://github.com/Backline/akka-http-metrics/releases/tag/0.4.1
