### ISSUE TITLE
Upgrade to use akka 2.4.8

### ISSUE THREAD

**Issue by devsprint** [Backline/akka-http-metrics#4]
akka 2.4.8 was released few days ago.

**Comment by adamdecaf** [comment]
@devsprint I've published `0.3.0` could you take it for a spin?

https://dl.bintray.com/backline/open-source/backline/akka-http-metrics_2.11/0.3.0/

**Comment by devsprint** [comment]
@adamdecaf sure, thanks a lot. I'll come back with update by tomorrow.

**Comment by devsprint** [comment]
@adamdecaf 0.3.0 is visible in the repo and could be downloadable.
I have run few tests and it seems to work ok (verification done with help of Console Reporter). I've verified the timerDirective only.

**Comment by adamdecaf** [comment]
Sweet. Thanks!
