### ISSUE TITLE
support for the new akka-http release

### ISSUE THREAD

**Issue by mazorigal** [Backline/akka-http-metrics#9]
Hi,

would you plan to provide support for the new akka-http releases ?

Thanks,

**Comment by adamdecaf** [comment]
@mazorigal Sure thing. I made https://github.com/Backline/akka-http-metrics/pull/10 and once it passes I'll release `0.4.0`.

**Comment by adamdecaf** [comment]
@mazorigal You should be able to pull `0.4.0` for scala 2.11 now. Let me know if you run into any issues.
